import {
  mysqlTable,
  serial,
  varchar,
  int,
  timestamp,
} from "drizzle-orm/mysql-core";

export const respondents = mysqlTable("respondents", {
  id: serial("id").primaryKey(),
  name: varchar("name", { length: 255 }).notNull(),
  department: varchar("department", { length: 255 }).notNull(),
  workDuration: varchar("work_duration", { length: 100 }).notNull(),
  q1: int("q1").notNull(),
  q2: int("q2").notNull(),
  q3: int("q3").notNull(),
  q4: int("q4").notNull(),
  q5: int("q5").notNull(),
  q6: int("q6").notNull(),
  q7: int("q7").notNull(),
  q8: int("q8").notNull(),
  q9: int("q9").notNull(),
  q10: int("q10").notNull(),
  q11: int("q11").notNull(),
  q12: int("q12").notNull(),
  q13: int("q13").notNull(),
  q14: int("q14").notNull(),
  q15: int("q15").notNull(),
  q16: int("q16").notNull(),
  q17: int("q17").notNull(),
  q18: int("q18").notNull(),
  q19: int("q19").notNull(),
  q20: int("q20").notNull(),
  q21: int("q21").notNull(),
  q22: int("q22").notNull(),
  q23: int("q23").notNull(),
  q24: int("q24").notNull(),
  q25: int("q25").notNull(),
  q26: int("q26").notNull(),
  q27: int("q27").notNull(),
  q28: int("q28").notNull(),
  q29: int("q29").notNull(),
  q30: int("q30").notNull(),
  q31: int("q31").notNull(),
  q32: int("q32").notNull(),
  q33: int("q33").notNull(),
  q34: int("q34").notNull(),
  q35: int("q35").notNull(),
  q36: int("q36").notNull(),
  q37: int("q37").notNull(),
  q38: int("q38").notNull(),
  q39: int("q39").notNull(),
  q40: int("q40").notNull(),
  q41: int("q41").notNull(),
  q42: int("q42").notNull(),
  q43: int("q43").notNull(),
  q44: int("q44").notNull(),
  q45: int("q45").notNull(),
  q46: int("q46").notNull(),
  q47: int("q47").notNull(),
  q48: int("q48").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export type Respondent = typeof respondents.$inferSelect;
export type InsertRespondent = typeof respondents.$inferInsert;
